version: "3"
services:
  parcel-lab-app:
    image: parcel-lab-app
    build: . # because im using my own image: parcel-lab-app that is why we need to build but if we have used image: node which is prebuilt then we didn't need the build command
    command: "npm start"
    ports:
      - "4000:5000"
    volumes:
      - .:/usr/src/app # has to be same as Dockerfile workdir. It is mapping the current path of the local mechine to /usr/src/app that enables nodemon to pickup any local changes
    depends_on:
      - "parcel_lab_db"
    environment:
      LISTEN_HOST: 0.0.0.0
      LISTEN_PORT: 5000
      MONGO_DB_URL: "mongodb://parcel_lab_db:27017/data"

  parcel_lab_db:
    image: "mongo"
    restart: always
    ports: # without this the db will run but we cannot connect to it locally using compas
      - "27017:27017"
    volumes:
      - mongo-data:/data/db # name of the volume can be anything but /data/db has to be the same because by default inside docker mongo container mongo db always saves everyting there
volumes:
  mongo-data:
